title = "Jeff Russell's Webstead"
# Using jpowellrussell.com as my baseURL screwed up my theming before, but
# having a null value makes the title link in the sidebar not work to take you
# to the main page, which sucks. I'm going to try the github.io address, which
# is undesirable, since I'll have to change it if/when I move to a new host, but
# let's see how it works
baseURL = "https://jpowellrussell.github.io"
languageCode = "en-us"
theme = "diary"
# copyright = "&copy; {year} Jeff Russell"
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 25
googleAnalytics = ""
enableRobotsTXT = true

[[menu.main]]
url = "/coaching"
name = "Coaching"
weight = 1
[[menu.main]]
url = "/books"
name = "Books"
weight = 2
[[menu.main]]
url = "/gaming"
name = "Gaming"
weight = 3
[[menu.main]]
url = "/leaves"
name = "Leaves"
weight = 4

# Not sure if the below will work, but worth trying out
[[menu.main.leaves]]
url = "/leaves/about"
name = "About"
weight = 1

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  subtitle = "My little corner of the web"
  favicon = ""
  description = "Jeff Russell's little corner of the web"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/jpowellrussell/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jeffprussell/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5

[comments]
  disqusShortname = "Jeff"
