title = "Jeff Russell's Webstead"
# Okay, including any baseurl variable seems to throw off the theming. My
# current best guess is that there's a mismatch between the url's Hugo puts
# together when it builds the site and the URLs github generates through its IO
# page. To get desired behavior from title link, I'll have to modify the layout
# for the sidebar.
baseURL = ""
languageCode = "en-us"
# With the 'theme' variable, the -t 'theme' argument is not needed when building
# the site
theme = "diary"
# copyright = "&copy; {year} Jeff Russell"
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 25
googleAnalytics = ""
enableRobotsTXT = true

[[menu.main]]
url = "/thinking"
name = "Thinking"
weight = 1
[[menu.main]]
url = "/reading"
name = "Reading"
weight = 2
[[menu.main]]
url = "/gaming"
name = "Gaming"
weight = 3
[[menu.main]]
url = "/coaching"
name = "Coaching"
weight = 4
[[menu.main]]
url = "/leaves"
name = "Leaves"
weight = 5

# In current form, the below doesn't add anything to the sidebar
[[menu.main.leaves]]
url = "/leaves/about"
name = "About"
weight = 1

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  subtitle = "My little corner of the web"
  favicon = ""
  description = "Jeff Russell's little corner of the web"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/jpowellrussell/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jeffprussell/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5

[comments]
  disqusShortname = "Jeff"
